name: Daily Commit
on:
  schedule:
    - cron: '0 0,8,16 * * *'  #  8 jam sekali

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Choose random line
        run: |
          line=$(shuf -n 1 content.txt)
          echo "$line" > content.txt
      - name: Commit changes
        run: git config user.email "zidanalmubarok652@gmail.com"
        run: git config user.name "kangzid"
        run: git add content.txt
        run: git commit -m "Daily commit: $line"
        run: git push
